CREATE TABLE `t_order` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `order_num` varchar(60) NOT NULL DEFAULT '' COMMENT '订单编号',
  `order_type` int(2) DEFAULT NULL COMMENT '订单类型',
  `photo` varchar(255) DEFAULT NULL COMMENT '订单照片',
  `order_time` datetime DEFAULT NULL COMMENT '预约时间',
  `add_time` datetime DEFAULT NULL COMMENT '下单时间',
  `status` int(1) DEFAULT NULL COMMENT '订单状态 0-未接单 1-已接单 2-工作中 3-已完成 4-已评价 5-已撤销',
  `customer_type` int(1) DEFAULT NULL COMMENT '客户类型',
  `customer_id` int(11) DEFAULT NULL COMMENT '下单客户编号',
   customer_name varchar(255) DEFAULT NULL COMMENT '下单客户名称',
   customer_lon varchar(20) DEFAULT NULL COMMENT '客户位置经度',
   customer_lat varchar(20) DEFAULT NULL COMMENT '客户位置维度',
  `remark` varchar(255) DEFAULT NULL COMMENT '订单备注',
  `main_tech_id` int(11) DEFAULT NULL COMMENT '主技师id',
  `second_tech_id` int(11) DEFAULT NULL COMMENT '合作技师id',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `unique_order_num` (`order_num`),
  KEY `main_tech_id` (`main_tech_id`),
  KEY `second_tech_id` (`second_tech_id`),
  CONSTRAINT `t_order_ibfk_1` FOREIGN KEY (`main_tech_id`) REFERENCES `t_technician` (`id`),
  CONSTRAINT `t_order_ibfk_2` FOREIGN KEY (`second_tech_id`) REFERENCES `t_technician` (`id`)
) DEFAULT CHARSET=utf8 COMMENT='订单表';