CREATE TABLE `t_construction` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) DEFAULT NULL COMMENT '订单id',
  `technician_id` int(11) DEFAULT NULL COMMENT '技师id',
  `rtposition_lon` varchar(20) DEFAULT NULL COMMENT '实时位置经度',
  `rtposition_lat` varchar(20) DEFAULT NULL COMMENT '实时位置纬度',
  `start_time` datetime DEFAULT NULL COMMENT '施工开始时间',
  `signin_time` datetime DEFAULT NULL COMMENT '签到时间',
  `end_time` datetime DEFAULT NULL COMMENT '施工结束时间',
  `brfore_pic_a` varchar(255) DEFAULT NULL COMMENT '施工前照片_1',
  `before_pic_b` varchar(255) DEFAULT NULL COMMENT '施工前照片_2',
  `before_pic_c` varchar(255) DEFAULT NULL COMMENT '施工前照片_3',
  `after_pic_a` varchar(255) DEFAULT NULL COMMENT '施工后照片_1',
  `after_pic_b` varchar(255) DEFAULT NULL COMMENT '施工后照片_2',
  `after_pic_c` varchar(255) DEFAULT NULL COMMENT '施工后照片_3',
  `after_pic_d` varchar(255) DEFAULT NULL COMMENT '施工后照片_4',
  `after_pic_e` varchar(255) DEFAULT NULL COMMENT '施工后照片_5',
  `after_pic_f` varchar(255) DEFAULT NULL COMMENT '施工后照片_6',
  `payfor` float(5,1) DEFAULT NULL COMMENT '结算金额',
  `workload` varchar(100) DEFAULT NULL COMMENT '工作量（多项用逗号隔开）',
  PRIMARY KEY (`Id`),
  KEY `order_id` (`order_id`),
  KEY `technician_id` (`technician_id`),
  CONSTRAINT `t_construction_ibfk_1` FOREIGN KEY (`order_id`) REFERENCES `t_order` (`Id`),
  CONSTRAINT `t_construction_ibfk_2` FOREIGN KEY (`technician_id`) REFERENCES `technician` (`id`)
) DEFAULT CHARSET=utf8 COMMENT='施工表';
