drop view t_work_detail_order_view;
create view t_work_detail_order_view  as
select o.id,o.order_num,
o.photo,
o.agreed_start_time,
o.agreed_end_time,
o.status ,
o.creator_type,
o.main_tech_id as tech_id,
o.before_photos ,
o.after_photos ,
o.start_time ,
o.end_time ,
o.sign_time ,
o.taken_time ,
o.add_time as create_time ,
o.type ,
o.coop_id ,
o.creator_id ,
o.creator_name ,
o.remark ,
o.product_status ,
o.reassignment_status ,
o.vehicle_model,
o.real_order_num,
o.license,
o.vin,
o.customer_name,
o.customer_phone,
o.turnover,
o.salesman
from t_order o
