com.autobon:
    getui:
        host: http://sdk.open.api.igexin.com/serviceex
        appId: zoCAUGD4Hi55CS6iW1OI77
        appKey: ESlofHVour7DmT7xy7cnJ9
        appSecret: 1VX09PPTcz7fdHBNYZVeB2
        masterSecret: c9qs7jpn6s7dAPDkFr23W4
    sms.gateway: http://114.215.172.92/message/messageSend # SMS Gateway
    test.token: technician:HM6GlQ4/4AXxoe2ZfZVM2Q==
    gm-path: /usr/bin # graphicsMagick工具路径
    env: TEST
    skill: 汽车贴膜,美容清洁,隐形车衣,车身改色
    baiduKey: lhFpgbOkc15RHjiexfP2aDhg
    upload.orderpic.path: /home/autobon/upload/orderpic

# Tomcat
server.port: 51234

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: Autobon.log

# spring
spring:
    profiles.active: dev
    freemarker.cache: true
    resources.cache-period: 7200

    datasource:
        url: jdbc:mysql://121.40.157.200:3306/autobondb?characterEncoding=utf8&useSSL=false
        username: autobon
        password: autobon
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 121.40.157.200
        port: 6379