com.autobon:
    getui.a:
        host: http://sdk.open.api.igexin.com/serviceex
        appId: zoCAUGD4Hi55CS6iW1OI77
        appKey: ESlofHVour7DmT7xy7cnJ9
        appSecret: 1VX09PPTcz7fdHBNYZVeB2
        masterSecret: c9qs7jpn6s7dAPDkFr23W4
    getui.b:
        host: http://sdk.open.api.igexin.com/serviceex
        appId: IED5iJnuVu8dklsGy35E54
        appKey: 22mn0WmsqS6k7omIUytIo4
        appSecret: QIBL2KCDIX5wbklRBLIxUA
        masterSecret: bMG7Hlt8Vd8sfifVetKqg4
    sms:
        appKey: 23310302
        appSecret: cd103a35b45d72bcab8f7b4eaf063fad
        templateId: SMS_4992411
        signature: 身份验证
        gateway: http://114.215.172.92/message/messageSend # SMS Gateway
    test.token: technician:HM6GlQ4/4AXxoe2ZfZVM2Q==
    test.adminToken: staff:ssEoVBwJ3rSYnidORQUvhQ==@123456
    test.coopToken: cooperator:pHpP/b+PYAbZ3bcSs7dqsQ==
    gm-path: /usr/bin # graphicsMagick工具路径
    # env: TEST
    baiduKey: lhFpgbOkc15RHjiexfP2aDhg
    uploadPath: ..

# Tomcat
server.port: 80

# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: Autobon.log

# spring
spring:
    profiles.active: dev

    datasource:
        type: com.mchange.v2.c3p0.ComboPooledDataSource
        url: jdbc:mysql://127.0.0.1:3306/autobondb?characterEncoding=utf8&useSSL=false
        user: autobon
        password: autobon
        checkoutTimeout: 6000 # 获取数据库连接等待超时时间,毫秒
        idleConnectionTestPeriod: 600 # 空闲连接检测时间, 秒
        initialPoolSize: 3 # 初始连接池连接数
        maxIdleTime: 1800 # 空闲连接保留最长时间,秒
        maxPoolSize: 10 # 连接池最大连接数
        minPoolSize: 3 # 连接池最小连接数
        maxStatements: 300 # 连接池为数据源缓存的PreparedStatement的总数
        maxStatementsPerConnection: 30 # 单个连接缓存的PreparedStatement数
    jpa:
        show-sql: true
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    redis:
        host: 127.0.0.1
        port: 6379
