CREATE TABLE `partner` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `title` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '加盟商名称',
  `province` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '省',
  `city` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '市',
  `distric` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '区县',
  `address` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '街道地址',
  `longitude` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '经度',
  `latitude` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '纬度',
  `phone` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '联系电话',
  `logo_url` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8_unicode_ci,
  `last_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL,
  `create_at` datetime DEFAULT NULL,
  `status` int(11) DEFAULT '0' COMMENT '0: 待审核，1：审核通过，2：审核未通过，3：帐户禁用',
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_UNIQUE` (`phone`),
  UNIQUE KEY `email_UNIQUE` (`email`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

# noinspection SqlNoDataSourceInspection
CREATE TABLE `partner_profile` (
  `id` int(11) NOT NULL COMMENT '合作商id',
  `name` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '企业名称',
  `short_name` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '企业简称',
  `biz_license_no` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '营业执照编号',
  `biz_license_photo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '营业执照照片',
  `legal_person_name` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '法人姓名',
  `legal_person_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '法人身份证编号',
  `legal_person_id_photo` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '法人身份证照片',
  `tax_id` varchar(125) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '纳税识别号',
  `invoice_header` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '发票抬头',
  `invoice_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '发票邮寄地址',
  `invoice_zip_code` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '邮政编码',
  `contact_name` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '联系人姓名',
  `contact_phone` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '联系人电话',
  `verify_at` datetime DEFAULT NULL COMMENT '审核时间',
  PRIMARY KEY (`id`),
  KEY `biz_license_ind` (`biz_license_no`),
  KEY `legal_person_id` (`legal_person_id`),
  KEY `legal_person_name` (`legal_person_name`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `technician` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone` varchar(45) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '姓名',
  `gender` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '性别',
  `id_no` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '身份证号',
  `id_photo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `avatar` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '头像',
  `bank` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '开户银行',
  `bank_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '开户行地址',
  `bank_card_no` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '银行卡号',
  `status` int(11) DEFAULT NULL COMMENT '0: 未审核，1：审核通过，2：审核未过，3：帐户禁用',
  `verify_at` datetime DEFAULT NULL COMMENT '审核时间',
  `last_login_at` datetime DEFAULT NULL COMMENT '上次登录时间',
  `last_login_ip` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '上次登录IP',
  `create_at` datetime DEFAULT NULL,
  `star` int(11) DEFAULT NULL COMMENT '星级',
  `vote_rate` float DEFAULT NULL COMMENT '好评率',
  PRIMARY KEY (`id`),
  UNIQUE KEY `phone_UNIQUE` (`phone`)
) DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
