com.autobon.getui:
    host: http://sdk.open.api.igexin.com/serviceex
    appId: q3v65zXcYtAWXBgUTnwLqA
    appKey: AKuV9yICF881J9EFP8wHGA
    appSecret: 1gAh5dM5yR76pTzZrK4w59
    masterSecret: FOlbVUBOEi7UWzYKVtStP4